### PR TITLE
Fixes the windows executable path for standalone mechanical

### PR DESCRIPTION
**Pull request by rajesh1359**
Fixes the typos in the documentation for launching standalone mechanical

https://github.com/pyansys/pymechanical/issues/212

### CODE REVIEW

**Review by koubaa — APPROVED** [review]

**Comment by koubaa** [comment]
@MaxJPRey @RobPasMue are you familiar with documentation build CI failures that look like this? It happened twice in a row:

Get:55 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 cups-bsd amd64 2.4.1op1-1ubuntu4.1 [37.0 kB]
Err:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9-common all 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.250.76.244 80]
Err:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9 amd64 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.250.76.244 80]
Err:19 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 ghostscript amd64 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.250.76.244 80]
Err:20 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 ghostscript-x amd64 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.250.76.244 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.55.0%7edfsg1-0ubuntu5.1_all.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.55.0~dfsg1-0ubuntu5.1_all.deb)  404  Not Found [IP: 52.250.76.244 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.250.76.244 80]
Fetched 161 MB in 22s (7357 kB/s)
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.250.76.244 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript-x_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript-x_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.250.76.244 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by RobPasMue** [comment]
> @MaxJPRey @RobPasMue are you familiar with documentation build CI failures that look like this? It happened twice in a row:
> 
> ```
> Get:55 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 cups-bsd amd64 2.4.1op1-1ubuntu4.1 [37.0 kB]
> Err:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9-common all 9.55.0~dfsg1-0ubuntu5.1
>   404  Not Found [IP: 52.250.76.244 80]
> Err:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9 amd64 9.55.0~dfsg1-0ubuntu5.1
>   404  Not Found [IP: 52.250.76.244 80]
> Err:19 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 ghostscript amd64 9.55.0~dfsg1-0ubuntu5.1
>   404  Not Found [IP: 52.250.76.244 80]
> Err:20 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 ghostscript-x amd64 9.55.0~dfsg1-0ubuntu5.1
>   404  Not Found [IP: 52.250.76.244 80]
> E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.55.0%7edfsg1-0ubuntu5.1_all.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.55.0~dfsg1-0ubuntu5.1_all.deb)  404  Not Found [IP: 52.250.76.244 80]
> E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.250.76.244 80]
> Fetched 161 MB in 22s (7357 kB/s)
> E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.250.76.244 80]
> E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript-x_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript-x_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.250.76.244 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```

Hi @koubaa! Yes, we've reported internally this failure. Looks like a transient error - we get these from time to time from the Azure Ubuntu archives. Let's hope it gets solved soon. Many other repos are suffering from it.

**Review by samigithub2022 — APPROVED** [review]

**Comment by RobPasMue** [comment]
Error has been tracked here: https://github.com/actions/runner-images/issues/7452

**Comment by koubaa** [comment]
@RobPasMue it's still failing on multiple reruns. Is it really a transient error?

**Comment by RobPasMue** [comment]
> @RobPasMue it's still failing on multiple reruns. Is it really a transient error?

Not transient as "sometimes works, sometimes doesn't"... it's more like the runners are having issues in their latest update. I can do a quick fix for now, and I'll rvert it as soon as its fixed

**Comment by koubaa** [comment]
@rajesh1359 thank you for the contribution!

**Pull request merged**
