### PR TITLE
fix doc

### LINKED ISSUE #202: Cannot launch embedded instance
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I'm trying to test the standard installation of PyMechanical (not dev mode) and launching an embedded instance fails:
image
I get the same issue whether I try with 231 or 232. The files that are mentioned in the error message do exist:
image
@koubaa Is there something I'm missing?

### 📝 Steps to reproduce

- install PyMechanical through pip
- type: 
```
from ansys.mechanical.core import App, global_variables
app = App(version=231)
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

231 or 232

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
ansys-api-mapdl==0.5.1
ansys-api-mechanical==0.1.0
ansys-api-meshing-prime==0.1.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-dpf-composites==0.1.0
ansys-dpf-core==0.7.4
ansys-dpf-gate==0.3.1
ansys-dpf-gatebin==0.3.1
ansys-dpf-post==0.3.0
ansys-grpc-dpf==0.7.1
ansys-mapdl-core==0.64.0
ansys-mapdl-reader==0.52.11
ansys-mechanical-core==0.7.1
ansys-meshing-prime==0.3.0
ansys-platform-instancemanagement==1.0.3
ansys-pythonnet==3.1.0rc1
appdirs==1.4.4
asttokens==2.2.1
backcall==0.2.0
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.2.1
clr-loader==0.2.5
colorama==0.4.6
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.6
decorator==5.1.1
entrypoints==0.4
executing==1.2.0
fonttools==4.39.2
geomdl==5.3.1
google-api-core==2.11.0
google-api-python-client==2.82.0
google-auth==2.16.3
google-auth-httplib2==0.1.0
googleapis-common-protos==1.59.0
grpcio==1.53.0
httplib2==0.22.0
idna==3.4
imageio==2.27.0
importlib-metadata==6.1.0
ipykernel==6.22.0
ipython==8.11.0
jedi==0.18.2
jupyter_client==7.4.9
jupyter_core==5.3.0
kiwisolver==1.4.4
matplotlib==3.7.1
matplotlib-inline==0.1.6
nest-asyncio==1.5.6
numpy==1.24.2
packaging==23.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.2.0
pooch==1.7.0
prompt-toolkit==3.0.38
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.4
pure-eval==0.2.2
pyansys-tools-versioning==0.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.14.0
pyiges==0.2.1
pyparsing==3.0.9
python-dateutil==2.8.2
pyvista==0.36.1
pywin32==306
pyzmq==25.0.2
requests==2.28.2
rsa==4.9
scipy==1.10.1
scooby==0.7.1
six==1.16.0
spyder-kernels==2.4.2
stack-data==0.6.2
tornado==6.2
tqdm==4.65.0
traitlets==5.9.0
uritemplate==4.1.1
urllib3==1.26.15
vtk==9.2.6
wcwidth==0.2.6
zipp==3.15.0
```

### PR DESCRIPTION
**Pull request by koubaa**
fixes #202

### CODE REVIEW

**Comment by koubaa** [comment]
@samigithub2022 @RobPasMue 
we will need to push a doc release once this lands.  Could one of you show me how to do that?

**Review by samigithub2022 — APPROVED** [review]

**Comment by samigithub2022** [comment]
> > @samigithub2022 @RobPasMue we will need to push a doc release once this lands. Could one of you show me how to do that?
> 
> @koubaa once this PR is merged to main, we can see the updated doc. There is a step (pages build and deployment) that runs after something is merged on to main. @RobPasMue

@koubaa - this is only for dev. for official release, we need to tag a release. @RobPasMue

**Comment by RobPasMue** [comment]
That's right. Release docs are pushed whenever we do a new release @koubaa. Dev docs will have the change. Do you need it in the release docs as well?

**Comment by RobPasMue** [comment]
If that's the case, we can hack something temporarily on the release branch but I'd suggest doing a new release.

**Pull request merged**
